/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_impsapps_impsengine_common_clib_Library */

#ifndef _Included_com_impsapps_impsengine_common_clib_Library
#define _Included_com_impsapps_impsengine_common_clib_Library
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_impsapps_impsengine_common_clib_Library
 * Method:    onMemoryWarning
 * Signature: (Lcom/impsapps/impsengine/common/androidlib/AppState;)V
 */
JNIEXPORT void JNICALL Java_com_impsapps_impsengine_common_clib_Library_onMemoryWarning
  (JNIEnv *, jclass);

/*
 * Class:     com_impsapps_impsengine_common_clib_Library
 * Method:    isDebugMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_impsapps_impsengine_common_clib_Library_isDebugMode
  (JNIEnv *, jclass);

/*
 * Class:     com_impsapps_impsengine_common_clib_Library
 * Method:    shouldLogMemoryLeaks
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_impsapps_impsengine_common_clib_Library_shouldLogMemoryLeaks
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
