/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_impsapps_impsengine_common_multitouch_TouchListener */

#ifndef _Included_com_impsapps_impsengine_common_multitouch_TouchListener
#define _Included_com_impsapps_impsengine_common_multitouch_TouchListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_impsapps_impsengine_common_multitouch_TouchListener
 * Method:    createNewTouchHandler
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_impsapps_impsengine_common_multitouch_TouchListener_createNewTouchHandler
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_impsapps_impsengine_common_multitouch_TouchListener
 * Method:    onTouchBegan
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_impsapps_impsengine_common_multitouch_TouchListener_onTouchBegan
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_impsapps_impsengine_common_multitouch_TouchListener
 * Method:    prepareOnTouchMoved
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_impsapps_impsengine_common_multitouch_TouchListener_prepareOnTouchMoved
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_impsapps_impsengine_common_multitouch_TouchListener
 * Method:    addTouchMoved
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_impsapps_impsengine_common_multitouch_TouchListener_addTouchMoved
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_impsapps_impsengine_common_multitouch_TouchListener
 * Method:    executeOnTouchMoved
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_impsapps_impsengine_common_multitouch_TouchListener_executeOnTouchMoved
  (JNIEnv *, jclass);

/*
 * Class:     com_impsapps_impsengine_common_multitouch_TouchListener
 * Method:    onTouchEnded
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_impsapps_impsengine_common_multitouch_TouchListener_onTouchEnded
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_impsapps_impsengine_common_multitouch_TouchListener
 * Method:    onTouchCanceled
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_impsapps_impsengine_common_multitouch_TouchListener_onTouchCanceled
  (JNIEnv *, jclass);

/*
 * Class:     com_impsapps_impsengine_common_multitouch_TouchListener
 * Method:    destroyTouchHandler
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_impsapps_impsengine_common_multitouch_TouchListener_destroyTouchHandler
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
