/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_impsapps_impsengine_common_openglrenderer_IASurfaceRenderer */

#ifndef _Included_com_impsapps_impsengine_common_openglrenderer_IASurfaceRenderer
#define _Included_com_impsapps_impsengine_common_openglrenderer_IASurfaceRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_impsapps_impsengine_common_openglrenderer_IASurfaceRenderer
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_impsapps_impsengine_common_openglrenderer_IASurfaceRenderer_onSurfaceCreated
  (JNIEnv *, jclass);

/*
 * Class:     com_impsapps_impsengine_common_openglrenderer_IASurfaceRenderer
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_impsapps_impsengine_common_openglrenderer_IASurfaceRenderer_onSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_impsapps_impsengine_common_openglrenderer_IASurfaceRenderer
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_impsapps_impsengine_common_openglrenderer_IASurfaceRenderer_onDrawFrame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
