#ifndef IAAutoreleasePool_Internal_h
#define IAAutoreleasePool_Internal_h

void IAAutoreleasePool_incrementShouldReleaseImmediatlyCount(void);
void IAAutoreleasePool_decrementShouldReleaseImmediatlyCount(void);

#endif
